version: '3.8'

services:
  python-dev:
    container_name: python-dev
    build: .
    volumes:
      - .:/app  # Mount the project directory
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1  # Ensures real-time logging
    command: ["tail", "-f", "/dev/null"]  # Keeps the container running
